//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        [Key]
        public int pro_id { get; set; }
        [Required(ErrorMessage ="Product Name Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Product Image Required")]
        public string Image { get; set; }
        [Required(ErrorMessage = "Product Description is Required")]
        [MinLength(length: 10, ErrorMessage = "Minimum charcters should be 10")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Price Name Is Required")]
        public Nullable<int> Price { get; set; }
        [Required(ErrorMessage = "Category Is Required")]
        public string Category { get; set; }
        public Nullable<int> Quantity { get; set; }
        [Required(ErrorMessage = "Short Description is Required")]
        [MinLength(length: 5, ErrorMessage = "Minimum charcters should be 5")]
        public string ShortDescription { get; set; }
        public Nullable<int> Category_id { get; set; }
    
        public virtual tbl_categoriess tbl_categoriess { get; set; }
    }
}
