//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_categoriess
    {
        public tbl_categoriess()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Category_id { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
